//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSScript.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("scriptlib")]
        public string ScriptLibDirectory {
            get {
                return ((string)(this["ScriptLibDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"CSScript.Core
System
System.Collections
System.Collections.Generic
System.ComponentModel.DataAnnotations
System.Diagnostics
System.Drawing
System.IO
System.Net
System.Net.Mail
System.Runtime.InteropServices
System.Security.Cryptography
System.Text
System.Xml")]
        public string Usings {
            get {
                return ((string)(this["Usings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Microsoft.CSharp.dll
System.dll
System.ComponentModel.DataAnnotations.dll
System.Core.dll
System.Data.dll
System.Data.DataSetExtensions.dll
System.Data.Linq.dll
System.Drawing.dll
System.Drawing.Design.dll
System.Net.dll
System.Numerics.dll
System.Security.dll
System.Web.dll
System.Windows.Forms.dll
System.Xml.dll
System.Xml.Linq.dll")]
        public string Imports {
            get {
                return ((string)(this["Imports"]));
            }
        }
    }
}
